export enum thingAPITypes {
  INIT_THING_SEARCH = "INIT_THING_SEARCH",
  LOADING_THING_SEARCH = "LOADING_THING_SEARCH",
  SUCCESS_THING_SEARCH = "SUCCESS_THING_SEARCH",
  FAILED_THING_SEARCH = "FAILED_THING_SEARCH",
}
